<Project>
    <!-- Post-build: copy runtime assets -->
    <Target Name="CopyRuntimeAssets" AfterTargets="Build">
        <Message Text="Copying runtime assets to output..." Importance="high"/>
        <!-- Copy App Configurations -->
        <Copy SourceFiles="src\ElectronicComponentCatalog.App\Configuration\appsettings.json" DestinationFolder="$(OutputPath)" SkipUnchangedFiles="true"/>
        <Copy SourceFiles="src\ElectronicComponentCatalog.App\Configuration\themesettings.json" DestinationFolder="$(OutputPath)" SkipUnchangedFiles="true"/>
        <!-- Copy SQLite Database -->
        <ItemGroup>
            <_Database Include="Data\Database\catalog.db"/>
        </ItemGroup>
        <Copy SourceFiles="@(_Database)" DestinationFolder="$(OutputPath)" SkipUnchangedFiles="true" Condition="Exists('%(FullPath)')"/>
    </Target>
    <!-- Optional: enforce editorconfig compliance -->
    <Target Name="EnforceCodeStyle" BeforeTargets="Build">
        <Message Text="Applying .editorconfig rules..." Importance="low"/>
    </Target>
    <!-- Make sure MSBuild always runs restore -->
    <Target Name="EnsureRestore"  BeforeTargets="Build">
        <MSBuild Projects="$(MSBuildProjectFile)" Targets="Restore"/>
    </Target>
    <Target Name="CopyAppConfig" AfterTargets="Build">
        <ItemGroup>
            <!-- <_AppConfigFiles Include="src\ElectronicComponentCatalog.App\Configuration\appsettings*.json"
                            Condition="Exists('%(FullPath)')"/> -->
            <_AppConfigFiles Include="Configuration\appsettings*.json" />
        </ItemGroup>
        <Copy SourceFiles="@(_AppConfigFiles)"
            DestinationFolder="$(OutputPath)"
            SkipUnchangedFiles="true"
            Condition="@( _AppConfigFiles ) != ''"/>
    </Target>      
</Project>  